services:
  mongo-express:
    user: root
    image: mongo-express:1.0-20-alpine3.19
    hostname: mongo-express
    container_name: mongo-express
    ports:
      - 8002:${MONGO_EXPRESS_PORT}
    env_file:
      - ./env/.env.mongo
    healthcheck:
      test: ["CMD-SHELL", "nc -z mongo-express ${MONGO_EXPRESS_PORT} || exit -1"]
      interval: 5s
      timeout: 10s
      retries: 10
    networks:
      parsnet:
        ipv4_address: 192.168.10.6
    links:
      - mongo
    depends_on:
      mongo:
        condition: service_healthy
    restart: always
