repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        name: trailing-whitespace

      - id: end-of-file-fixer
        name: end-of-file-fixer

      - id: check-added-large-files
        name: check-added-large-files

      - id: check-toml
        name: check-toml

      - id: check-yaml
        name: check-yaml

      - id: check-json
        name: check-json

      - id: check-xml
        name: check-xml
